project_id = "miwmgwcddhsxayglguuc"

[functions.auth]
verify_jwt = false

[functions.gemini-proxy]
verify_jwt = false

[functions.tmdb-proxy]
verify_jwt = false

[functions.rawg-proxy]
verify_jwt = false

[functions.openlibrary-proxy]
verify_jwt = false
